<template>

  <div id = "login-page">
    <head>
      <title> This is the Main Login Page </title>
    </head>

    <body>


    <div class = "split left">
      <div class = "centered-left">
        <img src="../assets/foodchop.png" class="logo-login">
        <br> 

        <div class = "student">
            <button class = "button"> <router-link to="/login-student">Student</router-link> </button>
            </div>

        <div class = "staff">
          <button class = "button" > <router-link to="/login-staff">Staff</router-link> </button>
          </div>

        
        
    </div>

    <div class = "split right">
      <div class = "centered-right">
        <!-- Gif placement -->
        <div class="loadingio-spinner-pulse-2y3o1uqx1kt"><div class="ldio-hv4tq3e0s57">
          <div></div><div></div><div></div>
          </div></div>
        <h1> NUS FoodChope </h1>

        <h2> Hostel Dining Made Easy </h2>

        <p> NUS FoodChope is an online platform developed to simplify the takeout process for all NUS hostel residents. 
          Try out this hassle-free food ordering system today! </p>
      </div>
        
        
      </div>
    </div>


    </body>
  </div>

 
</template>

<script>
// @ is an alias to /src
import firebase from "firebase"

export default {
  create() {
    console.log(firebase.auth().currentUser)
  }
}
</script>



<style scoped>

body {
  font-family: Arial;
  color: white;
}

.logo-login {
  width: 100%;
}

/* Setting font for right-side */
h1 { 
  color: #f1eeee;
  font-family: 'Raleway',sans-serif;
  font-size: 60px;
  font-weight: 800;
  line-height: 72px;
  margin: 0 0 24px;
  text-align: center;
  text-transform: uppercase;
  text-shadow: 2px 2px lightslategray;
  }

h2 { 
  color: #ffffff;
  font-family: 'Raleway',sans-serif;
  font-size: 30px;
  font-weight: 700;
  margin: 0 0 24px;
  text-align: center;
  text-shadow: 1px 1px lightslategray;
  }

p { 
  color: #f8f8f8;
  font-family: 'Raleway',sans-serif;
  font-size: 18px;
  font-weight: 500;
  line-height: 32px;
  margin: 0 0 24px; 
  }

.split {
  height: 100%;
  width: 70%;
  position: fixed;
  z-index: 1;
  top: 0;
  overflow-x: hidden;
  padding-top: 20px;
}

.left {
  left: 0;
  background-color: lightslategray;
}

.right {
  right: -20px;
  background-image:linear-gradient(to bottom,rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.75)), url(../assets/styles/background2.jpg);
  background-size: cover;
  
}

.centered-left {
  position: absolute;
  top: 50%;
  left: 22%;
  transform: translate(-50%, -50%);
  text-align: center;
}

.centered-right {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  text-align: center;
}

.centered img {
  width: 150px;
  border-radius: 50%;
}

.button{
  text-align: center;
  background-color: none;
  font-size: 19px;
  cursor: pointer;
  line-height: 12px;
  border: 1px solid black;
  border-radius: 4px;

}

.button:hover {
  box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
}


/* Gif CSS */

@keyframes ldio-hv4tq3e0s57-1 {
  0% { top: 36px; height: 128px }
  50% { top: 60px; height: 80px }
  100% { top: 60px; height: 80px }
}
@keyframes ldio-hv4tq3e0s57-2 {
  0% { top: 41.99999999999999px; height: 116.00000000000001px }
  50% { top: 60px; height: 80px }
  100% { top: 60px; height: 80px }
}
@keyframes ldio-hv4tq3e0s57-3 {
  0% { top: 48px; height: 104px }
  50% { top: 60px; height: 80px }
  100% { top: 60px; height: 80px }
}
.ldio-hv4tq3e0s57 div { position: absolute; width: 30px }.ldio-hv4tq3e0s57 div:nth-child(1) {
  left: 35px;
  background: #e15b64;
  animation: ldio-hv4tq3e0s57-1 1s cubic-bezier(0,0.5,0.5,1) infinite;
  animation-delay: -0.2s
}
.ldio-hv4tq3e0s57 div:nth-child(2) {
  left: 85px;
  background: #f8b26a;
  animation: ldio-hv4tq3e0s57-2 1s cubic-bezier(0,0.5,0.5,1) infinite;
  animation-delay: -0.1s
}
.ldio-hv4tq3e0s57 div:nth-child(3) {
  left: 135px;
  background: #abbd81;
  animation: ldio-hv4tq3e0s57-3 1s cubic-bezier(0,0.5,0.5,1) infinite;
  animation-delay: undefineds
}

.loadingio-spinner-pulse-2y3o1uqx1kt {
  width: 180px;
  height: 170px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-hv4tq3e0s57 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-hv4tq3e0s57 div {
   box-sizing: content-box;
    }
/* generated by https://loading.io/ */


</style>






    